//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vizedeneme6.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Admin
    {
        public int adminid { get; set; }
        public string eposta { get; set; }
        public string sifre { get; set; }
    }
}
